app:
    resource: "@AppBundle/Controller/"
    type:     annotation

file:
    resource: "@FileBundle/Resources/config/routing.yml"

user:
    resource: "@UserBundle/Resources/config/routing.yml"

form:
    resource: "@FormBundle/Resources/config/routing.yml"