login:
  path: /login
  defaults: { _controller: UserBundle:Security:login }

logout:
  path: /logout

register:
  path: /register
  defaults: { _controller: UserBundle:Security:register }

recover:
  path: /recover/{token}
  defaults: { _controller: UserBundle:Security:recover, token: null }